---
- name: "Installing jenv"
  homebrew: 
    name: jenv 
    state: latest
  tags:
    - always
    
- name: "Adding jenv to rc"
  blockinfile:
    dest: '{{ brew_user_home_dir }}/{{item}}'
    marker: "# {mark} jenv"
    block: |
      export PATH="$HOME/.jenv/bin:$PATH"
      if which jenv > /dev/null; then eval "$(jenv init -)"; fi
  with_items: ['.zshrc', '.bashrc']
  tags:
      - always

