---
- name: "Ensure Percona(Mysql) Server {{ mysql_formula }}"
  homebrew: 
    name: "{{ mysql_formula }}"
    state: latest
  tags:
    - percona57

- homebrew: 
    name: "{{ mysql_formula }}"
    state: unlinked
  tags:
    - percona57

- name: "Check mysql already installed"
  stat: 
    path: "{{ mysql_data_dir }}"
  register: mysql_data_dir_stat
  tags:
    - percona57

- name: "Create directories"
  file: 
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ mysql_etc_dir }}"
    - "{{ mysql_data_dir }}"
    - "{{ mysql_log_dir }}"
    - "{{ mysql_run_dir }}"
  tags:
    - percona57

- stat:
    path: "{{ mysql_etc_dir }}/my.cnf"
  register: state
  tags:
    - percona57

- name: "Create my.cnf"
  template: 
    src: my.cnf.j2
    dest: "{{ mysql_etc_dir }}/my.cnf"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
    mode: 0744
  when: not state.stat.exists
  tags:
    - percona57

- find: 
    paths: "{{ mysql_data_dir }}"
  register: mysql_data_dir_files
  tags:
    - percona56

- name: "Install db (mysqld --initialize-insecure)"
  shell: "{{ mysql_base_dir }}/bin/mysql_install_db --basedir={{ mysql_base_dir }} --datadir={{ mysql_data_dir }}"
  when: mysql_data_dir_files.matched|int == 0
  tags:
    - percona56

- stat: 
    path: "{{ homebrew_install_path }}/etc/supervisor.d/{{ mysql_supervisord_name }}.ini"
  register: state
  tags:
    - percona56

- name: "Create {{ homebrew_install_path }}/etc/supervisor.d/{{ mysql_supervisord_name }}.ini"
  template:
    src: supervisord.ini.j2
    dest: "{{ homebrew_install_path }}/etc/supervisor.d/{{ mysql_supervisord_name }}.ini"
  when: not state.stat.exists
  tags:
    - percona56

