---
- name: "Ensure redisdb"
  homebrew: 
    name: redis
    state: latest
  tags:
    - always

- name: "Create {{ brew_install_path }}/etc/supervisor.d/redisdb.ini"
  template:
    src: supervisord.ini.j2
    dest: "{{ brew_install_path }}/etc/supervisor.d/redisdb.ini"
  tags:
    - always
