---
- name: "Creates /etc/pf.anchors/local.devbrew.nginx"
  copy:
    dest: "/etc/pf.anchors/local.devbrew.nginx"
    owner: "root"
    content: |
      # redirect http
      rdr pass on lo0 inet proto tcp from any to self port 80 -> 127.0.0.1 port 1080
      rdr pass on en0 inet proto tcp from any to any port 80 -> 127.0.0.1 port 1080
      rdr pass on en1 inet proto tcp from any to any port 80 -> 127.0.0.1 port 1080
      # redirect https
      rdr pass on lo0 inet proto tcp from any to self port 443 -> 127.0.0.1 port 1443
      rdr pass on en0 inet proto tcp from any to any port 443 -> 127.0.0.1 port 1443
      rdr pass on en1 inet proto tcp from any to any port 443 -> 127.0.0.1 port 1443
      # eol
  become: yes
  tags:
    - always

- name: 'Adds rdr-anchor "local.devbrew.nginx" to /etc/pf.conf'
  lineinfile:
    path: '/etc/pf.conf'
    line: 'rdr-anchor "local.devbrew.nginx"'
    insertafter: '^rdr-anchor.*'
  become: yes
  tags:
    - always

- name: 'Adds load anchor "local.devbrew.nginx" from "/etc/pf.anchors/local.devbrew.nginx" to /etc/pf.conf'
  lineinfile:
    path: '/etc/pf.conf'
    line: 'load anchor "local.devbrew.nginx" from "/etc/pf.anchors/local.devbrew.nginx"'
    insertafter: '^load anchor.*'
  become: yes
  tags:
    - always
