---
- name: "Creates www directory"
  file: path={{ www_dir }} state=directory
- name: "Installing Nginx"
  homebrew: "name={{ item }} state=present"
  with_items:
    - nginx
- name: "Creates nginx.conf"
  template: src=nginx.conf.j2 dest={{ homebrew_install_path }}/etc/nginx/nginx.conf owner={{ www_user }} group={{ www_group }}
- name: "Creates servers/default.conf"
  template: src=servers/default.conf.j2 dest={{ homebrew_install_path }}/etc/nginx/servers/default.conf owner={{ www_user }} group={{ www_group }}
