---
- name: Ensure php taps are tapped.
  homebrew_tap: "tap={{ item }} state=present"
  with_items:
    - "homebrew/php"
  tags:
    - php71

- name: "Unlink all already installed php packages"
  shell: "brew list | grep php | xargs brew unlink"
  tags:
    - php71

- name: "Installing php71 with flags: {{ php71_flags }}"
  homebrew:
    name: php71 
    state: latest 
    install_options: "{{ php71_flags }}"
  tags:
    - php71

- name: "Installing php71 modules"
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items: "{{ php71_modules }}"
  tags:
    - php71

- name: "Remove outdated php71"
  shell: "brew upgrade --cleanup php71"
  ignore_errors: yes
  tags:
    - php71

- name: "Installing php71 pear packages modules"
  shell: "pear install {{ item }}"
  with_items: "{{ php71_pear_packages }}"
  tags:
    - php71

- stat:
    path: "{{ homebrew_install_path }}/etc/php/7.1/php-fpm.conf"
  register: state
  tags:
    - php71

- name: "Create php-fpm.conf"
  template: 
    src: "php-fpm.conf.j2"
    dest: "{{ homebrew_install_path }}/etc/php/7.1/php-fpm.conf"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
  when: not state.stat.exists
  tags:
    - php71

- stat: 
    path: "{{ homebrew_install_path }}/etc/php/7.1/php.ini"
  register: state
  tags:
    - php71

- name: "Create php.ini"
  template: 
    src: "php.ini.j2"
    dest: "{{ homebrew_install_path }}/etc/php/7.1/php.ini"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
  when: not state.stat.exists
  tags:
    - php71

- stat: 
    path: "{{ homebrew_install_path }}/etc/php/7.1/php-fpm-xdebug.conf"
  register: state
  tags:
    - php71

- name: "Create php-fpm-xdebug.conf"
  template: 
    src: php-fpm-xdebug.conf.j2
    dest: "{{ homebrew_install_path }}/etc/php/7.1/php-fpm-xdebug.conf"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
  when: not state.stat.exists
  tags:
    - php71

- stat: 
    path: "{{ homebrew_install_path }}/etc/php/7.1/php-xdebug.ini"
  register: state
  tags:
    - php71

- name: "Create php-xdebug.ini"
  template: 
    src: php-xdebug.ini.j2
    dest: "{{ homebrew_install_path }}/etc/php/7.1/php-xdebug.ini"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
  when: not state.stat.exists
  tags:
    - php71

- stat: 
    path: "{{ homebrew_install_path }}/etc/php/7.1/conf.d/ext-opcache.ini"
  register: state
  tags:
    - php71

- name: "Create ext-opcache.ini"
  template: 
    src: "ext-opcache.ini.j2"
    dest: "{{ homebrew_install_path }}/etc/php/7.1/conf.d/ext-opcache.ini"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
  when: not state.stat.exists
  tags:
    - php71

- name: "Unlink php71"
  homebrew: "name=php71 state=unlinked"
  ignore_errors: yes
  tags:
    - php71

- name: "Add symlink"
  shell: find /usr/local/Cellar/php71 -path '*/bin/php' | awk -F/ '{print "ln -fs " $0 " " "/usr/local/bin/"$5}' | bash
  tags:
    - php71

- name: add 71 to "php_versions" array
  set_fact: 
    php_versions: "{{ php_versions + [ '71' ] }} "
  tags:
    - php71

- stat: 
    path: "{{ homebrew_install_path }}/etc/supervisor.d/php71.ini"
  register: state
  tags:
    - php71

- name: "Create etc/supervisor.d/php71.ini"
  template:
    src: supervisord.ini.j2
    dest: "{{ homebrew_install_path }}/etc/supervisor.d/php71.ini"
  when: not state.stat.exists
  tags:
    - php71
