---
- name: "Installing golang"
  homebrew: 
    name: go
    state: present
  tags:
    - always
    
- name: "Adding GOPATH to env"
  blockinfile:
    dest: '{{ brew_user_home_dir }}/{{item}}'
    marker: "# {mark} golang"
    block: |
      export GOPATH="${HOME}/go"
      export PATH="${PATH}:${GOPATH}/bin"
  with_items: ['.zshrc', '.bashrc']
  tags:
    - always
