---
- name: "Ensure typing via pip"
  pip:
    name: typing
    state: present
  become: yes

- name: "Ensure Cheetah via pip"
  pip:
    name: Cheetah
    state: present
  become: yes

- name: "Ensure mongodb"
  homebrew:
    name: mongodb@3.6
    state: present

- name: Resolve mongodb_path
  shell: "{{ brew_brew_bin_path }}/brew --prefix mongodb@3.6"
  register: output

- name: Register mongodb_path
  set_fact:
    mongodb_path: "{{ output.stdout | trim }}"

- name: "Create {{ brew_install_path }}/etc/supervisor.d/mongodb.ini"
  template:
    src: supervisord.ini.j2
    dest: "{{ brew_install_path }}/etc/supervisor.d/mongodb.ini"
