---
- name: "Ensure typing via pip"
  pip:
    name: typing
    state: present
  tags:
  - always

- name: "Ensure Cheetah via pip"
  pip:
    name: Cheetah
    state: present
  tags:
  - always

- name: "Ensure mongodb"
  homebrew:
    name: mongodb@3.6
    state: present
  tags:
  - always

- name: "Create {{ brew_install_path }}/etc/supervisor.d/mongodb.ini"
  template:
    src: supervisord.ini.j2
    dest: "{{ brew_install_path }}/etc/supervisor.d/mongodb.ini"
  when: not state.stat.exists
  tags:
  - always
