---
- name: "Ensure typing via pip"
  pip:
    name: typing
    state: present

- name: "Ensure Cheetah via pip"
  pip:
    name: Cheetah
    state: present

- name: "Ensure PyYAML via pip"
  pip:
    name: PyYAML
    state: present

- name: "Ensure mongodb"
  homebrew:
    name: mongodb@3.6
    state: present

- name: Resolve mongodb_path
  shell: "{{ brew_brew_bin_path }}/brew --prefix mongodb@3.6"
  register: output

- name: Register mongodb_path
  set_fact:
    mongodb_path: "{{ output.stdout | trim }}"

- name: "Create {{ brew_install_path }}/etc/supervisor.d/mongodb.ini"
  template:
    src: supervisord.ini.j2
    dest: "{{ brew_install_path }}/etc/supervisor.d/mongodb.ini"

- name: "Adding mongodb to PATH in {{ brew_user_home_dir }}/{{item}}"
- name: "Updating rc"
  blockinfile:
    dest: '{{ brew_user_home_dir }}/{{item}}'
    marker: "# {mark} mongodb"
    block: |
      echo 'export PATH="{{ mongodb_path }}/bin:$PATH"' >> ~/.zshrc
  with_items: ['.zshrc', '.bashrc']

- name: Ensure internalQueryExecMaxBlockingSortBytes with 100302864
  shell: "echo 'db.adminCommand({setParameter: 1, internalQueryExecMaxBlockingSortBytes:100302864})' | mongo admin"