---
- name: Ensure php taps are untapped.
  homebrew_tap: "tap={{ item }} state=absent"
  with_items:
    - "sergeycherepanov/php"

- name: Ensure required taps are tapped.
  homebrew_tap: "tap={{ item }} state=present"
  with_items:
    - "digitalspacestdio/common"

- name: "Ensure zlib"
  homebrew:
    name: zlib
    state: latest

- name: "Resolve zlib path"
  shell: "brew --prefix zlib"
  register: result

- name: "Register zlib_path fact"
  set_fact: zlib_path="{{ result.stdout }}"

- name: "Installing Curl with openssl"
  homebrew: 
    name: digitalspacestdio/common/curl
    state: latest
    install_options: with-openssl,with-libssh2
  environment:
    ZLIB_PATH: "{{ zlib_path }}"
