sudo: true
os:
  - osx
branches:
  only:
    - master
matrix:
  include:
    - env: TAGS=php56,zsh
    - env: TAGS=php70,zsh
    - env: TAGS=php71,zsh
script:
  - travis_wait 30 $TRAVIS_BUILD_DIR/run.sh -v --tags "${TAGS}"
