---
- hosts: localhost
  vars: 
    - php_versions: []
  roles:
    - roles/homebrew
    - roles/percona-server-56
    - roles/fakesendmail
    - roles/dnsmasq
    - roles/curl
    - roles/zsh
    - roles/coreutils
    - roles/php-56
    - roles/php-70
    - roles/php-71
    - roles/nginx
    - roles/nginx-php-fpm
    - roles/redis
    - roles/nodejs
    - roles/compass
    - roles/less
    - roles/php-tools
