---

- name: "Ensure EFK directory"
  file:
    path: "{{ homebrew_install_path }}/etc/efk/td-agent/conf.d"
    state: directory
  tags:
    - always

- name: "Creates {{ homebrew_install_path }}/etc/efk/td-agent/conf.d/nginx.conf"
  template:
    src: td-agent.nginx.conf.j2
    dest: "{{ homebrew_install_path }}/etc/efk/td-agent/conf.d/nginx.conf"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
  tags:
    - always