---
#- name: "Remove old node packages"
#  homebrew: 
#    name: "{{ item }}"
#    state: absent
#  tags:
#    - nodejs
#  with_items:
#    - node
#    - npm
    
- name: "Installing nodejs"
  homebrew: 
    name: node 
    state: latest
#    install_options: "without-icu4c"
  tags:
    - nodejs

- name: "Setting fact"
  set_fact: 
    nodejs_installed: true
  tags:
    - nodejs
