---
- import_tasks: ssl.yml

- name: Find old configs
  find:
    paths: "{{ homebrew_install_path }}/etc/nginx/servers"
    patterns: "ph*.conf"
  register: old_php_nginx_config
  tags:
    - always

- name: Deleting old configs
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ old_php_nginx_config.files }}"
  tags:
    - always

- name: Print php_versions content
  debug: 
    var: php_versions
  tags:
    - always
    
- name: "Creates {{ homebrew_install_path }}/etc/nginx/dev.conf"
  template: 
    src: dev.conf.j2
    dest: "{{ homebrew_install_path }}/etc/nginx/dev.conf" 
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
  tags:
    - always

- name: "Creates {{ homebrew_install_path }}/etc/nginx/conf.d/default_server.conf"
  template: 
    src: default_server.conf.j2
    dest: "{{ homebrew_install_path }}/etc/nginx/conf.d/default_server.conf" 
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
  tags:
    - always

- name: "Creates {{ homebrew_install_path }}/etc/nginx/servers/{{item}}_{{root_domain}}.conf"
  template: 
    src: servers/php.conf.j2
    dest: "{{ homebrew_install_path }}/etc/nginx/servers/{{item}}_{{root_domain}}.conf" 
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
  with_items: "{{subdomains}}"
  tags:
    - always

- name: "Creates {{ homebrew_install_path }}/etc/nginx/custom_server.conf.tpl"
  template: 
    src: servers/custom_server.conf.tpl.j2
    dest: "{{ homebrew_install_path }}/etc/nginx/custom_server.conf.tpl" 
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
  tags:
    - always

- name: Cleanup installed nginx-error-pages
  file:
    path: "{{ homebrew_install_path }}/opt/nginx-error-pages"
    state: absent
  tags:
    - always

- name: Ensure nginx-error-pages
  git:
    repo: 'https://github.com/SergeyCherepanov/nginx-error-pages.git'
    dest: '{{ homebrew_install_path }}/opt/nginx-error-pages'
    version: 'master'
  tags:
    - always

#- name: "Creates {{ homebrew_install_path }}/etc/nginx/servers/{{item.1}}_{{item.0}}_{{root_domain}}.conf"
#  template: 
#    src: servers/php_version.conf.j2
#    dest: "{{ homebrew_install_path }}/etc/nginx/servers/{{item.1}}_{{item.0}}_{{root_domain}}.conf" 
#    owner: "{{ www_user }}"
#    group: "{{ www_group }}"
#  with_nested:
#    - "{{subdomains}}"
#    - "{{php_versions}}"
#  tags:
#    - always
  
# - name: "Copy the daemon configuration file into place."
#   shell: "cp $(brew list nginx | grep /homebrew.mxcl.nginx.plist$) /Library/LaunchDaemons/"
#   become: yes
#   become_method: sudo
# - name: "Start Nginx automatically."
#   shell: "launchctl load -w /Library/LaunchDaemons/homebrew.mxcl.nginx.plist"
#   become: yes
#   become_method: sudo
