---
- name: "Install crtgen tool"
  template: 
    src: crtgen.j2
    dest: "{{ brew_install_path }}/bin/crtgen"
    mode: u+rx
  tags:
  - always

- name: "Install hostnames tool"
  template: 
    src: "hostnames.j2"
    dest: "{{ brew_install_path }}/bin/hostnames"
    mode: u+rx
    trim_blocks: false
  tags:
  - always

- name: "Creates localCA directories"
  file:
    path: "{{item}}"
    state: directory
    mode: 0755
  with_items:
    - "{{ brew_install_path }}/etc/openssl/localCA/certs"
    - "{{ brew_install_path }}/etc/openssl/localCA/newcerts"
    - "{{ brew_install_path }}/etc/openssl/localCA/crl"
    - "{{ brew_install_path }}/etc/openssl/localCA/private"
  tags:
  - always

- stat:
    path: "{{ brew_install_path }}/etc/openssl/localCA/caconfig.cnf"
  register: state
  tags:
  - always

- name: "Creates ca config"
  template:
    src: ssl/caconfig.cnf.j2
    dest: "{{ brew_install_path }}/etc/openssl/localCA/caconfig.cnf"
  when: not state.stat.exists
  tags:
  - always

- name: "Creates config for domains"
  template:
    src: ssl/domain.cnf.j2
    dest: "{{ brew_install_path }}/etc/openssl/localCA/{{item}}_{{root_domain}}.cnf"
  with_items: "{{subdomains}}"
  tags:
  - always

- name: "Ensure /usr/share/ca-certificates/extra"
  file:
    path: "/usr/share/ca-certificates/extra"
    state: directory
    mode: 0755
  become: yes
  when: ansible_system == "Linux"
  tags:
  - always

- name: "Ensure symlink: {{ brew_install_path }}/etc/openssl/openssl.cnf"
  file:
    src: "/etc/ssl/openssl.cnf"
    dest: "{{ brew_install_path }}/etc/openssl/openssl.cnf"
    state: link
    force: yes
  when: ansible_system == "Linux"
  become: true
  tags:
  - always

- name: "Ensure symlink: {{ brew_install_path }}/etc/openssl/certs"
  file:
    src: "/etc/ssl/certs"
    dest: "{{ brew_install_path }}/etc/openssl/certs"
    state: link
    force: yes
  when: ansible_system == "Linux"
  become: true
  tags:
  - always

- name: "Absent { brew_install_path }}/etc/openssl/cert.pem"
  file:
    path: "{ brew_install_path }}/etc/openssl/cert.pem"
    state: absent
  when: ansible_system == "Linux"
  become: true
  tags:
  - always

- name: "Ensure symlink: {{ brew_install_path }}/etc/openssl/certs/ca-certificates.crt"
  file:
    src: "/etc/ssl/certs/ca-certificates.crt"
    dest: "{{ brew_install_path }}/etc/openssl/cert.pem"
    state: link
  when: ansible_system == "Linux"
  become: true
  tags:
  - always

- name: "Ensure symlink: {{ brew_install_path }}/etc/openssl/private"
  file:
    src: "/etc/ssl/private"
    dest: "{{ brew_install_path }}/etc/openssl/private"
    state: link
    force: yes
  when: ansible_system == "Linux"
  become: true
  tags:
  - always

- name: "Cheking if certificate already generated"
  stat:
    path: "{{ brew_install_path }}/etc/openssl/localCA/cacert.pem"
  register: state
  tags:
  - always

- name: "Generate the Certificate Authority (CA) certificate"
  shell: 'openssl req -x509 -newkey rsa:2048 -out {{ brew_install_path }}/etc/openssl/localCA/cacert.pem -outform PEM -days 1825 -nodes'
  when: not state.stat.exists
  environment:
    OPENSSL_CONF: "{{ brew_install_path }}/etc/openssl/localCA/caconfig.cnf"
  tags:
  - always

- name: "Adding CA certificate to keychain"
  shell: 'security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain {{ brew_install_path }}/etc/openssl/localCA/cacert.pem'
  become: true
  when: ansible_system == "Darwin"
  tags:
  - always

- stat:
    path: "{{ brew_install_path }}/etc/openssl/localCA/index.txt"
  register: state
  tags:
  - always

- name: "Create the Certificate Database"
  shell: "echo '01' > {{ brew_install_path }}/etc/openssl/localCA/serial && touch {{ brew_install_path }}/etc/openssl/localCA/index.txt"
  when: not state.stat.exists
  tags:
  - always

- name: "Copy root certificate /usr/share/ca-certificates/extra"
  copy:
    src: '{{ brew_install_path }}/etc/openssl/localCA/cacert.pem'
    dest: '/usr/local/share/ca-certificates/cacert.crt'
  become: yes
  when: ansible_system == "Linux"
  tags:
  - always
    
- name: "Generate keys and signing for domains"
  shell: '{{ brew_install_path }}/bin/crtgen {{item}}.{{root_domain}}'
  with_items: "{{subdomains}}"
  tags:
  - always

- name: "update-ca-certificates"
  shell: 'update-ca-certificates'
  become: yes
  when: ansible_system == "Linux"
  tags:
  - always
