---
- name: Ensure php taps are tapped.
  homebrew_tap: "tap={{ item }} state=present"
  with_items:
    - "homebrew/dupes"
    - "homebrew/php"
  tags:
    - php56

- name: "Unlink all already installed php packages"
  shell: "brew list | grep php | xargs brew unlink"
  tags:
    - php56

- name: "Remove previously installed php56 packages"
  shell: "brew list | grep ^php56 | xargs brew uninstall --ignore-dependencies --force"
  ignore_errors: yes
  tags:
    - reinstall
    - php56

- name: "Installing php56 with flags: {{ php56_flags }}"
  homebrew:
    name: php56
    state: present
    install_options: "{{ php56_flags }}"
  tags:
    - php56
  
- name: "Unlink all already installed php packages"
  shell: "brew list | grep php | xargs brew unlink --no-run-if-empty"
  tags:
    - php56

- name: "Installing php56 modules"
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ php56_modules }}"
  tags:
    - php56

- name: "Create php-fpm.conf"
  template: src=php-fpm.conf.j2 dest={{ homebrew_install_path }}/etc/php/5.6/php-fpm.conf owner={{ www_user }} group={{ www_group }}
  tags:
    - php56

- name: "Create php.ini"
  template: src=php.ini.j2 dest={{ homebrew_install_path }}/etc/php/5.6/php.ini owner={{ www_user }} group={{ www_group }}
  tags:
    - php56

- name: "Create ext-opcache.ini"
  template: src=ext-opcache.ini.j2 dest={{ homebrew_install_path }}/etc/php/5.6/conf.d/ext-opcache.ini owner={{ www_user }} group={{ www_group }}
  tags:
    - php56

- name: "Create ext-xdebug.ini"
  template: src=ext-xdebug.ini.j2 dest={{ homebrew_install_path }}/etc/php/5.6/conf.d/ext-xdebug.ini owner={{ www_user }} group={{ www_group }}
  tags:
    - php56

- name: "Unlink php56"
  homebrew: "name=php56 state=unlinked"
  ignore_errors: yes
  tags:
    - php56

- name: "Add symlink"
  shell: find /usr/local/Cellar/php56 -path '*/bin/php' | awk -F/ '{print "ln -fs " $0 " " "/usr/local/bin/"$5}' | bash
  tags:
    - php56

- name: add 56 to "php_versions" array
  set_fact: 
    php_versions: "{{ php_versions + [ '56' ] }} "
  tags:
    - php56
