---
- name: "Installing CoreUtils"
  homebrew: 
    name: coreutils
    state: present
  tags:
    - always

- name: "Adding coreutils to PATH in {{ brew_user_home_dir }}/.zshrc"
  blockinfile:
    dest: '{{ brew_user_home_dir }}/.zshrc'
    marker: "# {mark} coreutils PATH"
    block: |
      export PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"
  tags:
    - always

- name: "Adding coreutils to PATH in {{ brew_user_home_dir }}/.bashrc"
  blockinfile:
    dest: '{{ brew_user_home_dir }}/.bashrc'
    marker: "# {mark} coreutils PATH"
    block: |
      export PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"
  tags:
    - always
