---
- name: "Clean /tmp/powerline_fonts if exists"
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "/tmp/awesome-terminal-fonts"
    - "/tmp/powerline_fonts"
    - "/tmp/oh-my-zsh"
  ignore_errors: yes
  tags:
    - zsh

- name: "Downloading 'hack' font"
  git:
    repo: 'https://github.com/powerline/fonts.git'
    dest: '/tmp/powerline_fonts'
    version: 'master'
  tags:
    - zsh

- copy:
    src: '/tmp/powerline_fonts/Hack/'
    dest: '{{ ansible_env.HOME }}/Library/Fonts/'
  tags:
    - zsh

- name: "Downloading 'hack' font for terminal"
  git:
    repo: 'https://github.com/gabrielelana/awesome-terminal-fonts.git'
    dest: '/tmp/awesome-terminal-fonts'
    version: 'master'
  tags:
    - zsh

- name: "Installing 'hack' font"
  copy:
    src: '/tmp/awesome-terminal-fonts/build/'
    dest: '{{ ansible_env.HOME }}/.fonts/'
  tags:
    - zsh
 
- name: "Installing powerline-status via pip"
  pip:
    name: powerline-status
    state: present
    extra_args: --user
  tags:
    - zsh

- name: "Installing zsh via homebrew"
  homebrew: 
    name: zsh
    state: present
  tags:
    - zsh

- name: "Installing zsh-completions via homebrew"
  homebrew: 
    name: zsh-completions
    state: present
  tags:
    - zsh

- git:
    repo: 'https://github.com/sorin-ionescu/prezto.git'
    dest: '{{ ansible_env.HOME }}/.zprezto'
    version: 'master'
  tags:
    - zsh
  
#- name: "Configure zshrc: {{ ansible_env.HOME }}/.zshrc"
#  shell: |
#    setopt EXTENDED_GLOB
#    for rcfile in ~/.zprezto/runcoms/^README.md(.N); do
#      unlink ~/.${rcfile:t}
#      cp "$rcfile" ~/.${rcfile:t}
#    done
#  args:
#    executable: /usr/local/bin/zsh
#  tags:
#    - zsh

- stat: 
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: state
  tags:
    - zsh

- name: "Clean {{ ansible_env.HOME }}/.oh-my-zsh"
  file:
    state: absent
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  when: state.stat.exists
  tags:
    - zsh

- git:
    repo: 'https://github.com/robbyrussell/oh-my-zsh.git'
    dest: '/tmp/oh-my-zsh'
    version: 'master'
  tags:
    - zsh

- name: "Changing default shell to zsh "
  shell: 'chsh -s /bin/zsh {{ mac_user|default(ansible_env.USER) }}'
  become: true
  become_user: root
  tags:
    - zsh

- name: "Installing Oh My Zsh"
  shell: '/tmp/oh-my-zsh/tools/install.sh'
  environment:
    SHELL: /bin/zsh
  args:
    executable: /bin/zsh
  tags:
    - zsh

- name: "Adding homebrew to PATH in {{ ansible_env.HOME }}/.zshrc"
  blockinfile:
    create: yes
    dest: '{{ ansible_env.HOME }}/.zshrc'
    marker: "# {mark} homebrew PATH"
    block: |
      export PATH="/usr/local/sbin:$PATH"
  tags:
    - always

- name: "Adding aliases {{ ansible_env.HOME }}/.zshrc"
  blockinfile:
    create: yes
    dest: '{{ ansible_env.HOME }}/.zshrc'
    marker: "# {mark} export aliases"
    block: |
      if [[ -f ~/.aliases ]]; then
        source ~/.aliases
      fi
  tags:
    - always

- lineinfile:
    path: '{{ ansible_env.HOME }}/.zshrc'
    regexp: '^DEFAULT_USER=.*'
    line: 'DEFAULT_USER="$USER"'
  tags:
    - zsh

- name: "Adding Prezto modules to {{ ansible_env.HOME }}/.zpreztorc"
  blockinfile:
    dest: '{{ ansible_env.HOME }}/.zshrc'
    marker: "# {mark} Prezto Modules"
    block: |
      zstyle ':prezto:load' pmodule \
        'environment' \
        'terminal' \
        'editor' \
        'history' \
        'directory' \
        'spectrum' \
        'utility' \
        'completion' \
        'git' \
        'syntax-highlighting' \
        'history-substring-search' \
        'prompt'
      
      zstyle ':prezto:module:prompt' theme 'paradox'
  tags:
    - zsh

- name: "Creating .vim/autoload folder"
  file:
    path: "{{item}}"
    state: directory
    mode: 0755
  with_items:
    - "{{ ansible_env.HOME }}/.vim/autoload"
    - "{{ ansible_env.HOME }}/.vim/bundle"
  tags:
    - zsh

- name: "Install pathogen.vim"
  get_url:
    url: "https://tpo.pe/pathogen.vim"
    dest: "{{ ansible_env.HOME }}/.vim/autoload/pathogen.vim"
  tags:
    - zsh

- name: "Adding pathogen.vim to .vimrc"
  blockinfile:
    create: yes
    dest: '{{ ansible_env.HOME }}/.vimrc'
    marker: '" {mark} pathogen.vim'
    block: |
      execute pathogen#infect()
      syntax on
      filetype plugin indent on
  tags:
    - zsh

- name: "Adding locales to PATH in {{ ansible_env.HOME }}/.zshrc"
  blockinfile:
    dest: '{{ ansible_env.HOME }}/.zshrc'
    marker: "# {mark} locales PATH"
    insertbefore: BOF
    block: |
      export LC_ALL=en_US.UTF-8
      export LANG=en_US.UTF-8
      source $HOME/.fonts/*.sh
  tags:
    - zsh

- name: "Adding Prezto to {{ ansible_env.HOME }}/.zshrc"
  blockinfile:
    dest: '{{ ansible_env.HOME }}/.zshrc'
    marker: "# {mark} Prezto init"
    insertbefore: BOF
    block: |
      # Source Prezto.
      if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
        source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
      fi
      
      # Customize to your needs...
  tags:
    - zsh

- name: "Adding local_python to PATH in {{ ansible_env.HOME }}/.zshrc"
  blockinfile:
    dest: '{{ ansible_env.HOME }}/.zshrc'
    marker: "# {mark} local_python PATH"
    block: |
      export PATH="{{ ansible_env.HOME }}/Library/Python/2.7/bin:$PATH"
  tags:
    - zsh
      
- name: "Adding powerline to config {{ ansible_env.HOME }}/.zshrc"
  blockinfile:
    dest: '{{ ansible_env.HOME }}/.zshrc'
    marker: "# {mark} powerline"
    block: |
      source {{ ansible_env.HOME }}/Library/Python/2.7/lib/python/site-packages/powerline/bindings/zsh/powerline.zsh
  tags:
    - zsh
      
- name: "Adding powerline config {{ ansible_env.HOME }}/.vimrc"
  blockinfile:
    dest: '{{ ansible_env.HOME }}/.vimrc'
    marker: "# {mark} powerline"
    block: |
      python from powerline.vim import setup as powerline_setup
      python powerline_setup()
      python del powerline_setup
      set laststatus=2
  tags:
    - zsh
      
