---
- name: Ensure php taps are tapped.
  homebrew_tap: "tap={{ item }} state=present"
  with_items:
    - "kyslik/homebrew-php"
  tags:
    - php70

- name: "Unlink all already installed php packages"
  shell: "brew list | grep php | xargs brew unlink"
  tags:
    - php70

- name: "Installing php70 with flags: {{ php70_flags }}"
  homebrew: 
    name: php70 
    state: latest 
    install_options: "{{ php70_flags }}"
  tags:
    - php70

- name: "Installing php70 modules"
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items: "{{ php70_modules }}"
  tags:
    - php70

- name: "Remove outdated php70"
  shell: "brew upgrade --cleanup php70"
  ignore_errors: yes
  tags:
    - php70

- name: "Installing php70 pear packages modules"
  shell: "pear install {{ item }}"
  with_items: "{{ php70_pear_packages }}"
  tags:
    - php70

- name: "Add wrapper"
  template:
    src: "php.j2"
    dest: "{{ homebrew_install_path }}/bin/{{ php_version }}"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
    mode: 0755
  tags:
    - php70
#- stat:
#    path: "{{ homebrew_install_path }}/etc/php/7.0/php-fpm.conf"
#  register: state
#  tags:
#    - php70

- name: "Create php-fpm.conf"
  template: src=php-fpm.conf.j2 dest={{ homebrew_install_path }}/etc/php/7.0/php-fpm.conf owner={{ www_user }} group={{ www_group }}
#  when: not state.stat.exists
  tags:
    - php70

#- stat:
#    path: "{{ homebrew_install_path }}/etc/php/7.0/php.ini"
#  register: state
#  tags:
#    - php70

- name: "Create php.ini"
  template: src=php.ini.j2 dest={{ homebrew_install_path }}/etc/php/7.0/php.ini owner={{ www_user }} group={{ www_group }}
#  when: not state.stat.exists
  tags:
    - php70

#- stat:
#    path: "{{ homebrew_install_path }}/etc/php/7.0/php-fpm-xdebug.conf"
#  register: state
#  tags:
#    - php70

- name: "Create php-fpm-xdebug.conf"
  template: 
      src: php-fpm-xdebug.conf.j2
      dest: "{{ homebrew_install_path }}/etc/php/7.0/php-fpm-xdebug.conf"
      owner: "{{ www_user }}"
      group: "{{ www_group }}"
#  when: not state.stat.exists
  tags:
    - php70

#- stat:
#    path: "{{ homebrew_install_path }}/etc/php/7.0/php-xdebug.ini"
#  register: state
#  tags:
#    - php70


- name: "Create php-xdebug.ini"
  template:
    src: php.ini.j2
    dest: "{{ homebrew_install_path }}/etc/php/{{ php_version_num }}/php-xdebug.ini"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
#  when: not state.stat.exists
  tags:
    - php70

- blockinfile:
    dest: '{{ homebrew_install_path }}/etc/php/{{ php_version_num }}/php-xdebug.ini'
    marker: "; {mark} ansible xdebug"
    block: |
      [xdebug]
      zend_extension="/usr/local/opt/{{ php_version }}-xdebug/xdebug.so"
      xdebug.remote_enable=1
      xdebug.remote_autostart = 0
      xdebug.remote_connect_back = 0
      xdebug.remote_host=127.0.0.1
      xdebug.remote_port=92{{ php_version_num_int }}
      xdebug.profiler_enable=0
      xdebug.profiler_output_dir=/tmp/xdebug{{ php_version_num_int }}
      xdebug.idekey=PHPSTORM
      xdebug.overload_var_dump=0
      xdebug.max_nesting_level=500
  tags:
    - php70

#- stat:
#    path: "{{ homebrew_install_path }}/etc/php/7.0/conf.d/ext-opcache.ini"
#  register: state
#  tags:
#    - php70

- git:
    repo: 'https://github.com/tideways/php-profiler-extension.git'
    dest: "/tmp/xhprof{{php_version}}"
    version: 'master'
  tags:
    - php70

- name: "Install xhprof extension"
  shell: >
    {{ homebrew_install_path }}/opt/{{php_version}}/bin/phpize &&
    ./configure --with-php-config={{ homebrew_install_path }}/opt/{{php_version}}/bin/php-config &&
    make &&
    make install
  args:
    chdir: "/tmp/xhprof{{php_version}}"
  tags:
    - php70

- name: "Ensure ext-xhprof.ini"
  copy:
    content: "extension=tideways_xhprof.so"
    dest: "{{ homebrew_install_path }}/etc/php/{{ php_version_num }}/conf.d/ext-xhprof.ini"
  tags:
    - php70

- name: "Create ext-opcache.ini"
  template:
    src: ext-opcache.ini.j2
    dest: "{{ homebrew_install_path }}/etc/php/7.0/conf.d/ext-opcache.ini"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
#  when: not state.stat.exists
  tags:
    - php70

- name: "Unlink php70"
  homebrew: "name=php70 state=unlinked"
  ignore_errors: yes
  tags:
    - php70

- name: add '{{ php_version_num_int }}' to "php_versions" array
  set_fact: 
    php_versions: "{{ php_versions + [ php_version_num_int ] }}"
  tags:
    - php70

- debug:
    var: php_versions
  tags:
    - php70

#- stat:
#    path: "{{ homebrew_install_path }}/etc/supervisor.d/php70.ini"
#  register: state
#  tags:
#    - php70

- name: "Create etc/supervisor.d/php70.ini"
  template:
    src: supervisord.ini.j2
    dest: "{{ homebrew_install_path }}/etc/supervisor.d/php70.ini"
#  when: not state.stat.exists
  tags:
    - php70

- name: "Creates {{ homebrew_install_path }}/etc/efk/td-agent/conf.d/php{{ php_version_num }}.conf"
  template:
    src: td-agent.php.conf.j2
    dest: "{{ homebrew_install_path }}/etc/efk/td-agent/conf.d/php{{ php_version_num }}.conf"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
  tags:
    - php70
