---
- name: "Installing Percona(Mysql) Server (homebrew/versions/percona-server56)"
  homebrew: 
    name: "{{ mysql56_formula }}"
    state: present
  tags:
    - percona56

- name: "Get mysql cellar info"
  shell: "echo $(brew --cellar percona-server@5.6)/$(ls $(brew --cellar percona-server@5.6))"
  register: mysql56_cellar_stat
  tags:
    - percona56

- name: "Set "
  set_fact: 
    mysql56_cellar: "{{ mysql56_cellar_stat.stdout }}"
  tags:
    - percona56

- name: "Check mysql already installed"
  shell: "brew --cellar percona-server@5.6"
  stat: 
    path: "{{ mysql56_data_dir }}"
  register: mysql56_data_dir_stat
  tags:
    - percona56

- name: "Create directories"
  file: 
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ mysql56_etc_dir }}"
    - "{{ mysql56_data_dir }}"
    - "{{ mysql56_log_dir }}"
    - "{{ mysql56_run_dir }}"
  tags:
    - percona56

- name: "Create my.cnf"
  template: 
    src: my.cnf.j2
    dest: "{{ mysql56_etc_dir }}/my.cnf"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
    mode: 0744
  tags:
    - percona56

- name: "link percona-server"
  command: "brew link percona-server@5.6 --force"
  tags:
    - percona56

- name: "Install db (mysqld --initialize-insecure)"
  shell: "mysql_install_db --basedir={{ mysql56_cellar_stat.stdout }} --datadir={{ mysql56_data_dir }}"
  when: mysql56_data_dir_stat.stat.exists is defined and not mysql56_data_dir_stat.stat.exists
  tags:
    - percona56
