---
mysql56_formula: "percona-server@5.6"
mysql56_etc_dir: "{{ homebrew_install_path }}/etc/mysql/56"
mysql56_data_dir: "{{ homebrew_install_path }}/var/run/mysql/56"
mysql56_log_dir: "{{ homebrew_install_path }}/var/log/mysql/56"
mysql56_run_dir: "{{ homebrew_install_path }}/var/lib/mysql/56"

