---
- name: "Installing composer"
  homebrew: 
    name: composer
    state: present
    
- name: "Installing fxp/composer-asset-plugin:~1.3"
  shell: 'composer global require fxp/composer-asset-plugin:~1.3'

- name: "Installing phpmd"
  homebrew: 
    name: phpmd
    state: present

- name: "Link phpmd"
  homebrew: 
    name: phpmd
    state: linked

- name: "Installing phpcs"
  homebrew: 
    name: php-code-sniffer
    state: present

- name: "Link php-code-sniffer"
  homebrew: 
    name: php-code-sniffer
    state: linked
