---
- name: Ensure php taps are tapped.
  homebrew_tap: "tap={{ item }} state=present"
  with_items:
    - "homebrew/dupes"
    - "homebrew/php"
- name: "Installing php56 with fpm"
  homebrew: "name=php56 state=present install_options=with-fpm,with-mysql,without-apache,disable-opcache"
- name: "Unlink php56"
  homebrew: "name=php56 state=linked"
- name: "Installing php56-mcrypt"
  homebrew: "name=php56-mcrypt state=present"
- name: "Installing php56-intl"
  homebrew: "name=php56-intl state=present"
- name: "Installing php56-xdebug"
  homebrew: "name=php56-xdebug state=present"
- name: "Installing php56-redis"
  homebrew: "name=php56-redis state=present"
- name: "Create php-fpm.conf"
  template: src=php-fpm.conf.j2 dest={{ homebrew_install_path }}/etc/php/5.6/php-fpm.conf owner={{ www_user }} group={{ www_group }}
- name: "Create php.ini"
  template: src=php.ini.j2 dest={{ homebrew_install_path }}/etc/php/5.6/php.ini owner={{ www_user }} group={{ www_group }}
- name: "Unlink php56"
  homebrew: "name=php56 state=unlinked"
- name: "Creates {{ www_dir }}/dev56/info directory"
  file: path={{ www_dir }}/dev56/info state=directory
- name: "Create info.dev56 host"
  template: src=index.php dest={{ www_dir }}/dev56/info/index.php owner={{ www_user }} group={{ www_group }}
