---
- name: "Create fake_sendmail.sh"
  template: src=fake_sendmail.sh.j2 dest={{ homebrew_brew_bin_path }}/fake_sendmail.sh owner={{ www_user }} group={{ www_group }} mode=0744
- name: "Creates {{ ansible_env.HOME }}/mail directory"
  file: path={{ ansible_env.HOME }}/mail state=directory
