---
- stat: 
    path: "{{ brew_brew_bin_path }}/fake_sendmail.sh"
  register: state
  tags:
    - always

- name: "Create fake_sendmail.sh"
  template: 
    src: fake_sendmail.sh.j2
    dest: "{{ brew_brew_bin_path }}/fake_sendmail.sh"
    owner: "{{ brew_user }}"
    group: "{{ brew_group }}"
    mode: 0744
  when: not state.stat.exists
  tags:
    - always
  
- name: "Creates {{ brew_user_home_dir }}/mail directory"
  file:
    path: "{{ brew_user_home_dir }}/mail"
    state: directory
  tags:
    - always
