---
- name: "Installing DNSMASQ"
  homebrew: "name=dnsmasq state=present"
- name: "Truncate configuration file"
  shell: "echo '' > {{ homebrew_install_path }}/etc/dnsmasq.conf"
- name: "Adding *.dev55 zone to configuration file"
  shell: "echo 'address=/dev55/127.0.0.1' >> {{ homebrew_install_path }}/etc/dnsmasq.conf"
- name: "Adding *.dev56 zone to configuration file"
  shell: "echo 'address=/dev56/127.0.0.1' >> {{ homebrew_install_path }}/etc/dnsmasq.conf"
- name: "Adding *.dev70 zone to configuration file"
  shell: "echo 'address=/dev70/127.0.0.1' >> {{ homebrew_install_path }}/etc/dnsmasq.conf"
- name: "Adding *.loc zone to configuration file"
  shell: "echo 'address=/loc55/127.0.0.1' >> {{ homebrew_install_path }}/etc/dnsmasq.conf"
- name: "Adding *.loc zone to configuration file"
  shell: "echo 'address=/loc56/127.0.0.1' >> {{ homebrew_install_path }}/etc/dnsmasq.conf"
- name: "Adding *.loc zone to configuration file"
  shell: "echo 'address=/loc70/127.0.0.1' >> {{ homebrew_install_path }}/etc/dnsmasq.conf"
- name: "Creates /etc/resolver directory"
  file: path=/etc/resolver state=directory
  become: yes
  become_method: sudo
- name: "Configure *.dev55 resolver"
  shell: "echo 'nameserver 127.0.0.1' > /etc/resolver/dev55"
  become: yes
  become_method: sudo
- name: "Configure *.dev56 resolver"
  shell: "echo 'nameserver 127.0.0.1' > /etc/resolver/dev56"
  become: yes
  become_method: sudo
- name: "Configure *.dev70 resolver"
  shell: "echo 'nameserver 127.0.0.1' > /etc/resolver/dev70"
  become: yes
  become_method: sudo
- name: "Configure *.loc55 resolver"
  shell: "echo 'nameserver 127.0.0.1' > /etc/resolver/loc55"
  become: yes
  become_method: sudo
- name: "Configure *.loc56 resolver"
  shell: "echo 'nameserver 127.0.0.1' > /etc/resolver/loc56"
  become: yes
  become_method: sudo
- name: "Configure *.loc70 resolver"
  shell: "echo 'nameserver 127.0.0.1' > /etc/resolver/loc70"
  become: yes
  become_method: sudo
# - name: "Copy the daemon configuration file into place."
#   shell: "cp $(brew list dnsmasq | grep /homebrew.mxcl.dnsmasq.plist$) /Library/LaunchDaemons/"
#   become: yes
#   become_method: sudo
# - name: "Start Dnsmasq automatically."
#   shell: "launchctl load -w /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist"
#   become: yes
#   become_method: sudo
