---
- name: "Installing DNSMASQ"
  homebrew: 
    name: dnsmasq
    state: present
  tags:
    - always

- name: "Truncate configuration file"
  shell: "echo '' > {{ homebrew_install_path }}/etc/dnsmasq.conf"
  tags:
    - always

- name: "Creates /etc/resolver directory"
  file: path=/etc/resolver state=directory
  become: yes
  become_method: sudo
  tags:
    - always

- name: "Adding *.dev.com zone to dnsmasq configuration file"
  shell: "echo 'address=/dev.com/127.0.0.1' >> {{ homebrew_install_path }}/etc/dnsmasq.conf"
  tags:
    - always

- name: "Adding *.loc.com zone to dnsmasq configuration file"
  shell: "echo 'address=/loc.com/127.0.0.1' >> {{ homebrew_install_path }}/etc/dnsmasq.conf"
  tags:
    - always

- name: "Configure *.dev.com zone resolver"
  shell: "echo 'nameserver 127.0.0.1' > /etc/resolver/dev.com"
  become: yes
  tags:
    - always

- name: "Configure *.loc.com zone resolver"
  shell: "echo 'nameserver 127.0.0.1' > /etc/resolver/loc.com"
  become: yes
  tags:
    - always

# - name: "Copy the daemon configuration file into place."
#   shell: "cp $(brew list dnsmasq | grep /homebrew.mxcl.dnsmasq.plist$) /Library/LaunchDaemons/"
#   become: yes
#   become_method: sudo
# - name: "Start Dnsmasq automatically."
#   shell: "launchctl load -w /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist"
#   become: yes
#   become_method: sudo
