---
php_version: php73
php_version_num: 7.3
php_version_num_int: 73
php_flags: ""
php_dependencies:
php_modules:
    - intl
    - mcrypt
    - xdebug
    - redis
    - tidy
    - opcache
    - pdo-pgsql
    - xhprof
    - mongodb
    - apcu
    - gmp
    - imagick
php_pear_packages: []
