---
php70_flags: "with-homebrew-curl,with-pear"
php70_modules:
  - php70-intl
  - php70-mcrypt
  - php70-xdebug
  - php70-redis
  - php70-tidy
  - php70-opcache
  - php70-pdo-pgsql
php70_pear_packages: []
