---
php_version: php70
php_version_num: 7.0
php_version_num_int: 70
php_flags: ""
php_dependencies:
php_modules:
    - intl
    - mcrypt
    - xdebug
    - redis
    - tidy
    - opcache
    - pdo-pgsql
    - xhprof
    - mongodb
    - apcu
    - gpm
    - imagick
php_pear_packages: []
