---
- name: Ensure php taps are tapped.
  homebrew_tap: "tap={{ item }} state=present"
  with_items:
    - "homebrew/dupes"
    - "homebrew/php"
- name: "Installing php55 with fpm"
  homebrew: "name=php55 state=present install_options=with-fpm,with-mysql,without-apache,disable-opcache"
- name: "Unlink php55"
  homebrew: "name=php55 state=linked"
- name: "Installing php55-mcrypt"
#  homebrew: "name=php55-mcrypt state=present install_options=build-from-source"
  homebrew: "name=php55-mcrypt state=present"
- name: "Installing php55-intl"
  homebrew: "name=php55-intl state=present"
- name: "Installing php55-xdebug"
  homebrew: "name=php55-xdebug state=present"
- name: "Installing php55-redis"
  homebrew: "name=php55-redis state=present"
- name: "Create php-fpm.conf"
  template: src=php-fpm.conf.j2 dest={{ homebrew_install_path }}/etc/php/5.5/php-fpm.conf owner={{ www_user }} group={{ www_group }}
- name: "Create php.ini"
  template: src=php.ini.j2 dest={{ homebrew_install_path }}/etc/php/5.5/php.ini owner={{ www_user }} group={{ www_group }}
- name: "Unlink php55"
  homebrew: "name=php55 state=unlinked"
- name: "Creates {{ www_dir }}/dev55/info directory"
  file: path={{ www_dir }}/dev55/info state=directory
- name: "Create info.dev55 host"
  template: src=index.php dest={{ www_dir }}/dev55/info/index.php owner={{ www_user }} group={{ www_group }}
# - name: "Copy the daemon configuration file into place."
#   shell: "cp $(brew list php55 | grep /homebrew.mxcl.php55.plist$) {{ ansible_env.HOME }}/Library/LaunchAgents/homebrew.mxcl.php55.plist"
# - name: "Start php55 automatically."
#   shell: "launchctl load -w {{ ansible_env.HOME }}/Library/LaunchAgents/homebrew.mxcl.php55.plist"
