---
brew_brew_bin_path: "{{ brew_install_path }}/bin"

brew_installed_packages:
  - ssh-copy-id
  - pv
  - htop
  - mc
  - wget
  - mtr
  - nmap
  - watch
  - hg
  - bzr
  - p7zip
  - autoconf
  - gomplate
  - gettext
  - glances
  - json-table
  - pup
  - fswatch
  - shellcheck
  - libmcrypt
  - yarn
  - python@2

brew_upgrade_all_packages: no

brew_taps:
  - homebrew/cask
#  - homebrew/versions
  - homebrew/cask-fonts 

brew_cask_apps:
  - font-hack-nerd-font

brew_cask_appdir: /Applications

brew_use_brewfile: true
brew_brewfile_dir: '~'
