---
homebrew_install_path: /usr/local
homebrew_brew_bin_path: /usr/local/bin

homebrew_installed_packages:
  - ssh-copy-id
  - pv
  - htop
  - mc
  - wget
  - mtr
  - nmap
  - watch
  - hg
  - bzr
  - p7zip
  - autoconf
  - gomplate
  - gettext
  - glances
  - json-table
  - pup
  - fswatch
  - shellcheck

homebrew_upgrade_all_packages: no

homebrew_taps:
  - caskroom/cask
  - caskroom/versions
  - caskroom/fonts

homebrew_cask_apps:
  - font-hack-nerd-font
  - iterm2
  - java8

homebrew_cask_appdir: /Applications

homebrew_use_brewfile: true
homebrew_brewfile_dir: '~'
