---
- name: Absent previous installed xhgui
  file:
    path: "{{ brew_install_path }}/opt/xhgui"
    state: absent

- name: Ensure xhgui
  git:
    repo: "https://github.com/SergeyCherepanov/xhgui.git"
    dest: "{{ brew_install_path }}/opt/xhgui"
    version: "master_20180417"

- name: "Install xhgui"
  shell: >
    php {{ brew_install_path }}/bin/composer install
  args:
    chdir: "{{ brew_install_path }}/opt/xhgui"

- name: "Ensure {{ brew_install_path }}/etc/nginx/servers/xhgui.conf"
  template:
    src: nginx.xhgui.conf.j2
    dest: "{{ brew_install_path }}/etc/nginx/servers/xhgui.conf"

- name: "Ensure xhgui.local in /etc/hosts"
  lineinfile:
    path: '/etc/hosts'
    line: '127.0.0.1    xhgui.local'
  become: yes
