---
php_version: php56
php_version_num: 5.6
php_version_num_int: 56
php_flags: ""
php_dependencies:
php_modules:
    - intl
    - mcrypt
    - xdebug
    - redis
    - tidy
    - opcache
    - pdo-pgsql
    - xhprof
    - mongo
    - mongodb
    - apcu
    - gmp
    - imagick
php_pear_packages: []
