---
php_version: php56
php_version_num: 5.6
php_flags: "with-homebrew-curl,with-pear"
php_modules:
  - intl
  - mcrypt
  - xdebug
  - redis
  - tidy
  - opcache
  - pdo-pgsql
  - xhprof
  - mongodb
php_pear_packages: []
