---
php_version: php72
php_version_num: 7.2
php_version_num_int: 72
php_flags: ""
php_dependencies:
php_modules:
    - intl
    - mcrypt
    - xdebug
    - redis
    - tidy
    - opcache
    - pdo-pgsql
    - xhprof
    - mongodb
    - apcu
    - gmp
    - imagick
    - sodium
php_pear_packages: []
